### ISSUE TITLE
Variables - Slack module

### ISSUE THREAD

**Issue by Wajasful** [bitfocus/companion-module-slack-webhooks#4]
Good morning,

I've tried to use varibles to send messages but it seems that it's not working, the text sended is the name of the variable. It could be verry useful to send message using these variables.
Is it something to come on the next releases?

Thanks

**Comment by bryce-seifert** [comment]
It's currently not implemented, but I will add this to the next release

**Comment by Wajasful** [comment]
> It's currently not implemented, but I will add this to the next release

Cool it's a great news, I can't wait. Do you have an idea about the release date? 
Thanks for your great work 😉
